spring.datasource.url=jdbc:postgresql://localhost:5432/benefithub
spring.datasource.username=postgres
spring.datasource.password=postgres

jwt.secret=benefithub-secret-key-benefithub-secret-key-benefithub
jwt.expiration=360000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=8080